---
- name: Register Panel Admin
  ansible.builtin.include_tasks: register_panel_admin.yml

- name: Generate API Token
  ansible.builtin.include_tasks: generate_api_token.yml

- name: Get SSL_CERT
  ansible.builtin.include_tasks: get_ssl_cert.yml

- name: Setup Config Profile
  ansible.builtin.include_tasks: setup_config_profile.yml

- name: Setup Squads
  ansible.builtin.include_tasks: setup_squads.yml

- name: Setup Admin User
  ansible.builtin.include_tasks: setup_admin_user.yml
