---
- name: Create node_exporter user
  ansible.builtin.user:
    name: node_exporter
    shell: /bin/false
    create_home: false
    system: true

- name: Check for Node Exporter binary
  ansible.builtin.stat:
    path: /usr/local/bin/node_exporter
  register: node_exporter_bin

- name: Download Node Exporter
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.10.2/node_exporter-1.10.2.linux-{{ docker_arch_map[ansible_facts['architecture']] }}.tar.gz"
    dest: /tmp/node_exporter.tar.gz
    mode: "0644"
  when: not node_exporter_bin.stat.exists

- name: Uncompress Node Exporter
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp
    remote_src: true
    creates: "/tmp/node_exporter-1.10.2.linux-{{ docker_arch_map[ansible_facts['architecture']] }}"
  when: not node_exporter_bin.stat.exists

- name: Install Node Exporter binary
  ansible.builtin.copy:
    src: "/tmp/node_exporter-1.10.2.linux-{{ docker_arch_map[ansible_facts['architecture']] }}/node_exporter"
    dest: /usr/local/bin/node_exporter
    remote_src: true
    owner: node_exporter
    group: node_exporter
    mode: "0755"
  when: not node_exporter_bin.stat.exists

- name: Create Node Exporter Service
  ansible.builtin.copy:
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: "0644"
    content: |
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter --collector.systemd

      [Install]
      WantedBy=multi-user.target

- name: Enable and Start Node Exporter
  ansible.builtin.systemd:
    name: node_exporter
    enabled: true
    state: started
    daemon_reload: true

- name: Cleanup Node Exporter temp files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/node_exporter.tar.gz
    - "/tmp/node_exporter-1.10.2.linux-{{ docker_arch_map[ansible_facts['architecture']] }}"

- name: Allow Monitoring Port (from Monitoring IP only)
  vars:
    monitoring_ip: "{{ lookup('ansible.builtin.env', 'MONITORING_IP') | default('') }}"
  community.general.ufw:
    rule: allow
    port: "9100"
    proto: tcp
    from_ip: "{{ monitoring_ip }}"
  when: monitoring_ip is defined and monitoring_ip | length > 0
