---
- name: Reboot the server
  ansible.builtin.reboot:
    msg: "Rebooting to apply all updates"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 1
    post_reboot_delay: 30
    test_command: whoami
  when: reboot_infra | default('false') | bool
